# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Article.create(title:"Title 1", author: "Scott Fox", description:"Article description 1", date:"January 11, 2019", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo donec enim diam vulputate ut pharetra sit amet. Accumsan lacus vel facilisis volutpat est. Arcu odio ut sem nulla pharetra diam. Duis at tellus at urna condimentum mattis pellentesque. Sagittis aliquam malesuada bibendum arcu vitae elementum. Dignissim suspendisse in est ante. Eu consequat ac felis donec et odio pellentesque. Magna fermentum iaculis eu non. Sed faucibus turpis in eu mi. Ut pharetra sit amet aliquam. Auctor neque vitae tempus quam pellentesque nec. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n

Id aliquet risus feugiat in ante metus dictum at tempor. Nibh mauris cursus mattis molestie a iaculis. Volutpat est velit egestas dui id ornare. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Tortor consequat id porta nibh venenatis cras sed felis. Elit at imperdiet dui accumsan. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Blandit aliquam etiam erat velit scelerisque in dictum. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mus mauris vitae ultricies leo integer. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Blandit massa enim nec dui. Orci phasellus egestas tellus rutrum tellus. Auctor elit sed vulputate mi sit amet. Dolor sit amet consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sem nulla pharetra diam sit.\nAc felis donec et odio. In nisl nisi scelerisque eu ultrices.")

Article.create(title:"Title 2", author: "Scott Fox", description:"Article description 2", date:"January 12, 2019", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo donec enim diam vulputate ut pharetra sit amet. Accumsan lacus vel facilisis volutpat est. Arcu odio ut sem nulla pharetra diam. Duis at tellus at urna condimentum mattis pellentesque. Sagittis aliquam malesuada bibendum arcu vitae elementum. Dignissim suspendisse in est ante. Eu consequat ac felis donec et odio pellentesque. Magna fermentum iaculis eu non. Sed faucibus turpis in eu mi. Ut pharetra sit amet aliquam. Auctor neque vitae tempus quam pellentesque nec. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n

Id aliquet risus feugiat in ante metus dictum at tempor. Nibh mauris cursus mattis molestie a iaculis. Volutpat est velit egestas dui id ornare. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Tortor consequat id porta nibh venenatis cras sed felis. Elit at imperdiet dui accumsan. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Blandit aliquam etiam erat velit scelerisque in dictum. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mus mauris vitae ultricies leo integer. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Blandit massa enim nec dui. Orci phasellus egestas tellus rutrum tellus. Auctor elit sed vulputate mi sit amet. Dolor sit amet consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sem nulla pharetra diam sit.\nAc felis donec et odio. In nisl nisi scelerisque eu ultrices.")

Article.create(title:"Title 3", author: "Scott Fox", description:"Article description 3", date:"January 13, 2019", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo donec enim diam vulputate ut pharetra sit amet. Accumsan lacus vel facilisis volutpat est. Arcu odio ut sem nulla pharetra diam. Duis at tellus at urna condimentum mattis pellentesque. Sagittis aliquam malesuada bibendum arcu vitae elementum. Dignissim suspendisse in est ante. Eu consequat ac felis donec et odio pellentesque. Magna fermentum iaculis eu non. Sed faucibus turpis in eu mi. Ut pharetra sit amet aliquam. Auctor neque vitae tempus quam pellentesque nec. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n

Id aliquet risus feugiat in ante metus dictum at tempor. Nibh mauris cursus mattis molestie a iaculis. Volutpat est velit egestas dui id ornare. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Tortor consequat id porta nibh venenatis cras sed felis. Elit at imperdiet dui accumsan. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Blandit aliquam etiam erat velit scelerisque in dictum. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mus mauris vitae ultricies leo integer. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Blandit massa enim nec dui. Orci phasellus egestas tellus rutrum tellus. Auctor elit sed vulputate mi sit amet. Dolor sit amet consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sem nulla pharetra diam sit.\nAc felis donec et odio. In nisl nisi scelerisque eu ultrices.")

Article.create(title:"Title 4", author: "Scott Fox", description:"Article description 4", date:"January 14, 2019", content:"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo donec enim diam vulputate ut pharetra sit amet. Accumsan lacus vel facilisis volutpat est. Arcu odio ut sem nulla pharetra diam. Duis at tellus at urna condimentum mattis pellentesque. Sagittis aliquam malesuada bibendum arcu vitae elementum. Dignissim suspendisse in est ante. Eu consequat ac felis donec et odio pellentesque. Magna fermentum iaculis eu non. Sed faucibus turpis in eu mi. Ut pharetra sit amet aliquam. Auctor neque vitae tempus quam pellentesque nec. Pellentesque habitant morbi tristique senectus et netus et malesuada.\n

Id aliquet risus feugiat in ante metus dictum at tempor. Nibh mauris cursus mattis molestie a iaculis. Volutpat est velit egestas dui id ornare. Lorem ipsum dolor sit amet consectetur adipiscing elit pellentesque habitant. Tortor consequat id porta nibh venenatis cras sed felis. Elit at imperdiet dui accumsan. Facilisi nullam vehicula ipsum a arcu cursus vitae congue. Blandit aliquam etiam erat velit scelerisque in dictum. Consectetur adipiscing elit ut aliquam purus sit amet luctus. Mus mauris vitae ultricies leo integer. Pellentesque diam volutpat commodo sed egestas egestas fringilla phasellus. Blandit massa enim nec dui. Orci phasellus egestas tellus rutrum tellus. Auctor elit sed vulputate mi sit amet. Dolor sit amet consectetur adipiscing elit. Lorem ipsum dolor sit amet consectetur. Ultrices tincidunt arcu non sodales neque sodales ut etiam sit. Sem nulla pharetra diam sit.\nAc felis donec et odio. In nisl nisi scelerisque eu ultrices.")